#!WDDEFAULTIMPORTS
 SELECT DISTINCT ?taxon_id ?parent_id ?taxon_name ?taxon_rank  ?x ?p ?o {
              ?taxon_id <http://www.wikidata.org/prop/direct/P225> ?taxon_name;
                        <http://www.wikidata.org/prop/direct/P105>/rdfs:label ?taxon_rank.

              ?taxon_id <http://www.wikidata.org/prop/P171> ?x.
              ?x ?p ?o .

              FILTER (lang(?taxon_rank) = 'en')
            } LIMIT 10