#!WDDEFAULTIMPORTS
SELECT ?compound_id ?taxon_id ?reference_id
        WHERE {
            ?compound_id     p:P703 ?pp703;
                             wdt:P31 ?type.

            ?pp703           ps:P703 ?taxon_id;
                             prov:wasDerivedFrom/pr:P248 ?reference_id.

            VALUES ?type { wd:Q11173 wd:Q43460564 wd:Q59199015 } # chemical entity or group of stereoisomers
        }