#!WDDEFAULTIMPORTS
SELECT DISTINCT ?structure ?structure_inchikey ?taxon ?taxon_name ?reference ?reference_doi WHERE {
  ?structure wdt:P235 ?structure_inchikey; # get the inchikey
    p:P703 _:b5. # statement found in taxon
  _:b5 ps:P703 ?taxon; # get the taxon
    (prov:wasDerivedFrom/pr:P248) ?reference. # get the reference
  ?taxon wdt:P225 ?taxon_name. # get the taxon scientific name
  ?reference wdt:P356 ?reference_doi; # get the reference DOI
}